fix(ingestion): Fix scope of `.Values.globals` in ingestion
Because we're in a `range` inside `datahub-ingestion-cron`,
we can't access global values via `{{ .Values.global...`
Instead, we need `{{ $.Values...`.  Otherwise, we get
an error:

```
Error: template: datahub/charts/datahub-ingestion-cron/templates/cron.yaml:78:34: executing "datahub/charts/datahub-ingestion-cron/templates/cron.yaml" at <.Values.global.nodeSelector>: nil pointer evaluating interface {}.global
helm.go:84: [debug] template: datahub/charts/datahub-ingestion-cron/templates/cron.yaml:78:34: executing "datahub/charts/datahub-ingestion-cron/templates/cron.yaml" at <.Values.global.nodeSelector>: nil pointer evaluating interface {}.global
```

Fix so that it uses globals or the cron specific `nodeSelector`
and `tolerations` instead of triggering a nil pointer error